### ISSUE TITLE
Luego de completar campos erroneamente, los valores de esos campos deberían borrarse (permitiendo que el usuario los complete nuevamente)

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-barbero-mendez-fabian#7]
![imagen](https://user-images.githubusercontent.com/8345007/174503459-943c5fd4-450e-40b6-b66c-db1da5a72bb4.png)

El primero HP es el único que se volvio a 0. El resto quedo con letras.

**Comment by MaxiBarberoo** [comment]
Issue Resuelto
